include(InstallRequiredSystemLibraries)

set(CPACK_PACKAGE_CONTACT "maxsharov07@gmail.com")
set(CPACK_PACKAGE_VERSION_MAJOR ${BANKING_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${BANKING_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${BANKING_VERSION_PATCH})
set(CPACK_PACKAGE_VERSION_TWEAK ${BANKING_VERSION_TWEAK})
set(CPACK_PACKAGE_VERSION ${BANKING_VERSION})
set(CPACK_PACKAGE_DESCRIPTION_FILE ${CMAKE_CURRENT_SOURCE_DIR}/DESCRIPTION)
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Static C++ banking library")

set(CPACK_RESOURCE_FILE_LICENSE ${CMAKE_CURRENT_SOURCE_DIR}/LICENSE)
set(CPACK_RESOURCE_FILE_README ${CMAKE_CURRENT_SOURCE_DIR}/README.md)

set(CPACK_RPM_PACKAGE_NAME "banking-devel")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_GROUP "banking")
set(CPACK_RPM_CHANGELOG_FILE ${CMAKE_CURRENT_SOURCE_DIR}/ChangeLog.md)
set(CPACK_RPM_PACKAGE_RELEASE 1)

set(CPACK_DEBIAN_PACKAGE_NAME "libbanking-dev")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "cmake (>= 3.0)")
set(CPACK_DEBIAN_PACKAGE_RELEASE 1)

include(CPack)
